[package]
name = "ngspice-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ngspice-rs-sys = { version = "0.1", path = "../ngspice-rs-sys" }
once_cell = "1.9"
